###################################################################
# LICENSE
#
# Copyright 2020 United Kingdom Atomic Energy Authority
#
# Licensing terms of this software have yet to be approved.
###################################################################

TARGET=cov

include Makefile.inc

LIBRARIES_STATIC = LorenzAttractor/cov/LorenzAttractor$(LIBEXT)

ifdef EFDA_MARTe_DIR
LIBRARIES_STATIC+=BaseLib2GAM/cov/BaseLib2GAMTest$(LIBEXT)
endif